-- Sample data for Recipe Management System
-- This file contains sample ingredients, recipes, and categories for testing

-- Insert sample ingredient categories
INSERT INTO ingredient_categories (id, name, display_order) VALUES
  (gen_random_uuid(), 'Vegetables', 1),
  (gen_random_uuid(), 'Fruits', 2),
  (gen_random_uuid(), 'Dairy', 3),
  (gen_random_uuid(), 'Meat', 4),
  (gen_random_uuid(), 'Grains', 5),
  (gen_random_uuid(), 'Spices', 6),
  (gen_random_uuid(), 'Oils', 7),
  (gen_random_uuid(), 'Condiments', 8),
  (gen_random_uuid(), 'Baking', 9),
  (gen_random_uuid(), 'Snacks', 10);

-- Note: Replace 'YOUR_USER_ID' with actual user UUID when inserting for specific users
-- Sample ingredients (you'll need to replace with actual user_id)
-- Example structure:
/*
INSERT INTO ingredients (id, user_id, name, quantity, unit, category, expiry_date, notes) VALUES
  (gen_random_uuid(), 'YOUR_USER_ID', 'Tomatoes', 5, 'pieces', 'Vegetables', CURRENT_DATE + interval '7 days', 'Fresh from market'),
  (gen_random_uuid(), 'YOUR_USER_ID', 'Onions', 3, 'pieces', 'Vegetables', CURRENT_DATE + interval '14 days', NULL),
  (gen_random_uuid(), 'YOUR_USER_ID', 'Garlic', 1, 'bulb', 'Vegetables', CURRENT_DATE + interval '30 days', NULL),
  (gen_random_uuid(), 'YOUR_USER_ID', 'Olive Oil', 1, 'bottle', 'Oils', CURRENT_DATE + interval '180 days', 'Extra virgin'),
  (gen_random_uuid(), 'YOUR_USER_ID', 'Salt', 1, 'kg', 'Spices', NULL, NULL),
  (gen_random_uuid(), 'YOUR_USER_ID', 'Black Pepper', 100, 'g', 'Spices', NULL, NULL),
  (gen_random_uuid(), 'YOUR_USER_ID', 'Chicken Breast', 500, 'g', 'Meat', CURRENT_DATE + interval '3 days', 'Keep refrigerated'),
  (gen_random_uuid(), 'YOUR_USER_ID', 'Milk', 2, 'liters', 'Dairy', CURRENT_DATE + interval '5 days', NULL),
  (gen_random_uuid(), 'YOUR_USER_ID', 'Eggs', 12, 'pieces', 'Dairy', CURRENT_DATE + interval '14 days', NULL),
  (gen_random_uuid(), 'YOUR_USER_ID', 'Flour', 2, 'kg', 'Baking', CURRENT_DATE + interval '90 days', 'All-purpose'),
  (gen_random_uuid(), 'YOUR_USER_ID', 'Sugar', 1, 'kg', 'Baking', NULL, NULL),
  (gen_random_uuid(), 'YOUR_USER_ID', 'Pasta', 500, 'g', 'Grains', CURRENT_DATE + interval '365 days', 'Penne'),
  (gen_random_uuid(), 'YOUR_USER_ID', 'Rice', 5, 'kg', 'Grains', CURRENT_DATE + interval '180 days', 'Basmati'),
  (gen_random_uuid(), 'YOUR_USER_ID', 'Cheese', 200, 'g', 'Dairy', CURRENT_DATE + interval '21 days', 'Cheddar'),
  (gen_random_uuid(), 'YOUR_USER_ID', 'Butter', 250, 'g', 'Dairy', CURRENT_DATE + interval '30 days', NULL);
*/

-- Sample recipes with embeddings
-- Note: Embeddings would typically be generated by the backend service
-- Example structure:
/*
INSERT INTO recipes (id, user_id, title, description, ingredients, instructions, cuisine_type, taste_profile, preparation_time, cooking_time, servings, difficulty, source_type, raw_text) VALUES
  (
    gen_random_uuid(),
    'YOUR_USER_ID',
    'Classic Spaghetti Carbonara',
    'A traditional Italian pasta dish with eggs, cheese, and bacon',
    '[
      {"name": "spaghetti", "quantity": 400, "unit": "g"},
      {"name": "eggs", "quantity": 4, "unit": "pieces"},
      {"name": "bacon", "quantity": 200, "unit": "g"},
      {"name": "parmesan cheese", "quantity": 100, "unit": "g"},
      {"name": "black pepper", "quantity": 1, "unit": "tsp"},
      {"name": "salt", "quantity": 1, "unit": "tsp"}
    ]'::jsonb,
    '1. Cook spaghetti according to package instructions
2. Fry bacon until crispy
3. Beat eggs with grated cheese
4. Drain pasta, mix with bacon
5. Remove from heat and quickly stir in egg mixture
6. Season with pepper and serve immediately',
    'Italian',
    'savory',
    10,
    15,
    4,
    'easy',
    'manual',
    NULL
  ),
  (
    gen_random_uuid(),
    'YOUR_USER_ID',
    'Chicken Stir Fry',
    'Quick and healthy Asian-inspired chicken and vegetable stir fry',
    '[
      {"name": "chicken breast", "quantity": 500, "unit": "g"},
      {"name": "bell peppers", "quantity": 2, "unit": "pieces"},
      {"name": "onion", "quantity": 1, "unit": "piece"},
      {"name": "garlic", "quantity": 3, "unit": "cloves"},
      {"name": "soy sauce", "quantity": 3, "unit": "tbsp"},
      {"name": "vegetable oil", "quantity": 2, "unit": "tbsp"}
    ]'::jsonb,
    '1. Cut chicken into bite-sized pieces
2. Slice vegetables
3. Heat oil in wok or large pan
4. Cook chicken until golden
5. Add garlic and cook 30 seconds
6. Add vegetables and stir fry 3-4 minutes
7. Add soy sauce and toss well
8. Serve hot with rice',
    'Asian',
    'savory',
    15,
    10,
    4,
    'easy',
    'manual',
    NULL
  ),
  (
    gen_random_uuid(),
    'YOUR_USER_ID',
    'Chocolate Chip Cookies',
    'Classic American cookies with chocolate chips',
    '[
      {"name": "flour", "quantity": 2, "unit": "cups"},
      {"name": "butter", "quantity": 200, "unit": "g"},
      {"name": "sugar", "quantity": 150, "unit": "g"},
      {"name": "brown sugar", "quantity": 150, "unit": "g"},
      {"name": "eggs", "quantity": 2, "unit": "pieces"},
      {"name": "vanilla extract", "quantity": 1, "unit": "tsp"},
      {"name": "chocolate chips", "quantity": 300, "unit": "g"},
      {"name": "baking soda", "quantity": 1, "unit": "tsp"},
      {"name": "salt", "quantity": 0.5, "unit": "tsp"}
    ]'::jsonb,
    '1. Preheat oven to 180°C (350°F)
2. Cream butter with both sugars
3. Beat in eggs and vanilla
4. Mix flour, baking soda, and salt separately
5. Combine wet and dry ingredients
6. Fold in chocolate chips
7. Drop spoonfuls onto baking sheet
8. Bake 10-12 minutes until golden
9. Cool on rack',
    'American',
    'sweet',
    15,
    12,
    24,
    'easy',
    'manual',
    NULL
  ),
  (
    gen_random_uuid(),
    'YOUR_USER_ID',
    'Tomato Basil Soup',
    'Comforting and creamy tomato soup with fresh basil',
    '[
      {"name": "tomatoes", "quantity": 1, "unit": "kg"},
      {"name": "onion", "quantity": 1, "unit": "piece"},
      {"name": "garlic", "quantity": 3, "unit": "cloves"},
      {"name": "vegetable broth", "quantity": 2, "unit": "cups"},
      {"name": "fresh basil", "quantity": 1, "unit": "bunch"},
      {"name": "cream", "quantity": 100, "unit": "ml"},
      {"name": "olive oil", "quantity": 2, "unit": "tbsp"},
      {"name": "salt", "quantity": 1, "unit": "tsp"},
      {"name": "pepper", "quantity": 0.5, "unit": "tsp"}
    ]'::jsonb,
    '1. Sauté chopped onion and garlic in olive oil
2. Add chopped tomatoes and cook 10 minutes
3. Add broth and simmer 20 minutes
4. Blend until smooth
5. Stir in cream and torn basil
6. Season with salt and pepper
7. Serve hot with crusty bread',
    'Italian',
    'savory',
    10,
    30,
    4,
    'easy',
    'manual',
    NULL
  ),
  (
    gen_random_uuid(),
    'YOUR_USER_ID',
    'Vegetable Fried Rice',
    'Quick and delicious fried rice with mixed vegetables',
    '[
      {"name": "cooked rice", "quantity": 4, "unit": "cups"},
      {"name": "mixed vegetables", "quantity": 2, "unit": "cups"},
      {"name": "eggs", "quantity": 2, "unit": "pieces"},
      {"name": "soy sauce", "quantity": 3, "unit": "tbsp"},
      {"name": "garlic", "quantity": 2, "unit": "cloves"},
      {"name": "green onions", "quantity": 3, "unit": "stalks"},
      {"name": "vegetable oil", "quantity": 3, "unit": "tbsp"}
    ]'::jsonb,
    '1. Heat oil in wok or large pan
2. Scramble eggs and set aside
3. Sauté garlic until fragrant
4. Add vegetables and stir fry 3-4 minutes
5. Add rice and break up any clumps
6. Add soy sauce and mix well
7. Add eggs back in
8. Garnish with green onions and serve',
    'Asian',
    'savory',
    10,
    10,
    4,
    'easy',
    'manual',
    NULL
  );
*/

-- Instructions for using this file:
-- 1. Create a user account through the application
-- 2. Get the user_id from the auth.users table
-- 3. Replace 'YOUR_USER_ID' in the above INSERT statements with your actual user_id
-- 4. Run the modified SQL statements in your Supabase SQL editor

-- Example query to get your user_id after registration:
-- SELECT id, email FROM auth.users WHERE email = 'your@email.com';

-- To generate embeddings for recipes, you'll need to run the backend service
-- which will automatically create embeddings for new recipes
